### ISSUE TITLE
how to add gas into transaction

### ISSUE THREAD

**Issue by nhanth87** [nosofa/uniswap-v2-py#6]
Hi,
Can we add gas cost when call transaction like swap_exact_eth_for_tokens()?

**Comment by nhanth87** [comment]
HI @nosofa,
I have a patch for gas price estimation but it's based on joequin patch,
Can you please accept Joequin patch so I can send PR for my patch
many thanks

Br,
TN

**Comment by nosofa** [comment]
done :)
